name: Build Mod

on: [ workflow_dispatch ]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Sync bundles
        env:
          BAIDU_APP_ID: ${ { secrets.BAIDU_APP_ID } }
          BAIDU_KEY: ${ { secrets.BAIDU_KEY } }
        run: |
          ./gradlew syncBundle
          echo "Git status:"
          echo $(git status --porcelain)
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Github Actions"
            git add ./assets/bundles/*
            git commit -m "Automatic bundle update"
            git push
          fi